version: "3.7"

services:
  ptpro-public-module:
    image: fe-ptpro-public
    build:
      context: .
      dockerfile: docker/dockerfile
    container_name: fe-ptpro-public-module
    hostname: 'localhost'
    restart: "no"
    tty: true
    working_dir: /usr/www/app/src/modules/
    environment:
      NG_CLI_ANALYTICS: "false"
    ports:
      - "4800:4800"
    volumes:
      - ./module:/usr/www/app/src/modules/public
    #command: sh -c "/tmp/submodules.sh"
    networks:
      - app-network
      
#Docker networks
networks:
  app-network:
    driver: bridge